apiVersion: v1
kind: Service
metadata:
  name: zomboid
spec:
  type: NodePort
  ports:
    - name: steam
      protocol: UDP
      port: 8766
    - name: rcon
      port: 27015
    - name: game
      protocol: UDP
      port: 16261
      nodePort: 30005
